# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs410Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BadWords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='GoodWords',
            field=models.TextField(),
        ),
    ]
