# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs410Project', '0002_auto_20170423_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ReviewsPerLevel',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.TextField(default=''),
        ),
    ]
